# Generated by Django 3.2.1 on 2022-03-12 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 12, 11, 59, 44, 712658)),
        ),
    ]
