# Generated by Django 3.2.5 on 2022-03-20 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_weight_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 20, 14, 7, 28, 738661)),
        ),
    ]
